IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = 
            OBJECT_ID(N'dbo.as_system_getSQL_form'))
	DROP PROCEDURE dbo.as_system_getSQL_form
GO

create proc dbo.as_system_getSQL_form  @code nvarchar(32), @overwrite bit = 1 as
select top 1 'declare @formID int, @datatypeID int; set @formID = null; ' + CHAR(13)+CHAR(10)
	+ 'select top 1 @formID = f.id from as_forms as f where f.code = ' + isnull('''' + f.code + '''', 'null') + ' order by f.id; ' + CHAR(13)+CHAR(10)
	+ 'begin try' + CHAR(13)+CHAR(10)
		+ 'if @formID > 0 begin ' + CHAR(13)+CHAR(10) 
			+ (case @overwrite when 1 then
				'update as_forms set [code] = ' + isnull('''' + replace(f.code, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
					+ ',[title] = ' + isnull('''' + replace(f.title, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10)
					+ ',[subtitle] = ' + isnull('''' + replace(f.subtitle, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
					+ ',[resultMessage] = ' + isnull('''' + replace(f.resultMessage, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
					+ ',[successURL] = ' + isnull('''' + replace(f.successURL, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
					+ ',[makeup] = ' + isnull('''' + replace(f.makeup, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
					+ ',[hideFormAfterSubmit] = ' + isnull(cast(f.hideFormAfterSubmit as nvarchar), 'null')
					+ ',[buttonText] = ' + isnull('''' + replace(f.buttonText, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
					+ ',[users] = ' + isnull('''' + replace(f.users, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
					+ ',[roles] = ' + isnull('''' + replace(f.roles, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10)
					+ ' where id = @formID;' + CHAR(13)+CHAR(10) 
					+ 'print N''Форма ' + @code + ' обновлена'''	+ CHAR(13)+CHAR(10)
				else 'print N''Форма ' + @code + ' существует и не будет перезаписана'''	+ CHAR(13)+CHAR(10) end)
		+ ' end; else begin' + CHAR(13)+CHAR(10) 
			+ ' insert into as_forms ([code],[title],[subtitle],[resultMessage],[successURL],[makeup]'+ CHAR(13)+CHAR(10) 
				+ ',[hideFormAfterSubmit],[buttonText],[users],[roles]) VALUES ( ' + CHAR(13)+CHAR(10)
				+ stuff(COALESCE(', ''' + RTRIM(replace(f.code, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(f.title, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10) 
					+ COALESCE(', ''' + RTRIM(replace(f.subtitle, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(f.resultMessage, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(f.successURL, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10) 
					+ COALESCE(', ''' + RTRIM(replace(f.makeup, '''', '''''')) + '''', ', null')
					+ COALESCE(', ' + RTRIM(f.hideFormAfterSubmit), ', null')
					+ COALESCE(', ''' + RTRIM(replace(f.buttonText, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10) 
					+ COALESCE(', ''' + RTRIM(replace(f.users, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(f.roles, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+'); ' + CHAR(13)+CHAR(10) 
				, 1, 2, '')
			+ 'select @formID = scope_identity();' + CHAR(13)+CHAR(10)
			+ 'print N''Форма ' + @code + ' добавлена''' + CHAR(13)+CHAR(10)
			+ 'end;' + CHAR(13)+CHAR(10)			
	+ 'end try' + CHAR(13)+CHAR(10)
	+ 'begin catch' + CHAR(13)+CHAR(10)
		+ 'print N''При обновлении\добавлении формы ' + @code + ' возникла ошибка: '' + error_message()'	+ CHAR(13)+CHAR(10)
	+ 'end catch' + CHAR(13)+ CHAR(13)+CHAR(10)
	+ (case @overwrite when 1 then
		'begin try' + CHAR(13)+CHAR(10)
			+ 'delete from as_formCols where as_formCols.formID = @formID;' + CHAR(13)+CHAR(10)
			+ 'print N''Колонки формы ' + @code + ' удалены'''	+ CHAR(13)+CHAR(10)
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'print N''При удалении колонок формы ' + @code + ' возникла ошибка: '' + error_message()'	+ CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+ CHAR(13)+CHAR(10)
	else 'print N''Имеющиеся колонки не будут изменены''' + CHAR(13)+ CHAR(13)+CHAR(10) end)
	+ (select 'begin try' + CHAR(13)+CHAR(10)
		+ (case @overwrite when 0 then
				'if (not exists(select 1 from as_formCols where code =''' + fc.code + '''))' + CHAR(13)+CHAR(10)
				+ 'begin' + CHAR(13)+CHAR(10)
				else '' end)
		+ 'set @datatypeID = null; ' + CHAR(13)+CHAR(10)
		+ 'select @datatypeID = d.id from as_dataTypes as d where d.code = '
			 + isnull('''' + replace((select d.code from as_dataTypes as d where fc.datatypeID = d.id), '''', '''''') + '''', 'null') + '; ' + CHAR(13)+CHAR(10)
		+ ' insert into as_formCols ([formID],[code],[title],[placeholder],[tooltip],[ord],[datatypeID]' + CHAR(13)+CHAR(10)
			+ ',[isRequired],[sqlSource],[width],[dependentCols]) VALUES ( @formID, ' + CHAR(13)+CHAR(10)		
				+ stuff(COALESCE(', ''' + RTRIM(replace(fc.code, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(fc.title, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(fc.placeholder, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(fc.tooltip, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ' + RTRIM(fc.ord), ', null')
					+ COALESCE(', @datatypeID', ', null')
					+ COALESCE(', ' + RTRIM(fc.isRequired), ', null')
					+ COALESCE(', ''' + RTRIM(replace(fc.sqlSource, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(fc.width, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(fc.dependentCols, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
				, 1, 2, '') + ');' + CHAR(13)+CHAR(10)
		+ 'print N''Колонка ' + fc.code + ' формы добавлена'''	+ CHAR(13)+CHAR(10)
		+ (case @overwrite when 0 then
				+ 'end' + CHAR(13)+CHAR(10) 
				+ 'else ' + CHAR(13)+CHAR(10) 
				+ 'print N''Колонка ' + fc.code + ' формы уже существует и не будет перезаписана''' + CHAR(13)+CHAR(10)
				else '' end)
	+ 'end try' + CHAR(13)+CHAR(10)
	+ 'begin catch' + CHAR(13)+CHAR(10)
		+ 'print N''При добалении колонки ' + fc.code + ' формы возникла ошибка: '' + error_message()'	+ CHAR(13)+CHAR(10)
	+ 'end catch' + CHAR(13)+ CHAR(13)+CHAR(10) from as_formCols as fc where f.id = fc.formID FOR XML PATH (''),TYPE).value('.','NVARCHAR(MAX)')
	+ dbo.as_system_getSQL_procs ('fm_' + @code + '[_]', @overwrite) + CHAR(13)+CHAR(10)
	+'--Конец скрипта'
	as Result from as_forms as f where f.code = @code order by f.id;				
