create proc as_system_getSQL_dashboards @code nvarchar(32) as
declare @code nvarchar(20)
set @code = 'forAdmin'
select top 1 'declare @dashboardID int; set @dashboardID = null; ' + CHAR(13)+CHAR(10)
	+ 'create table #errors (type nvarchar(32), code nvarchar(256), message nvarchar(2048));' + CHAR(13)+CHAR(10)
	+ 'select top 1 @dashboardID = d.id from as_dashboards as d where d.code = ' + isnull('''' + d.code + '''', 'null') + ' order by d.id; ' + CHAR(13)+CHAR(10)
	+ 'begin try' + CHAR(13)+CHAR(10)
		+ 'if @dashboardID > 0 begin ' + CHAR(13)+CHAR(10) 
			+'update as_dashboards set [code] = ' + isnull('''' + replace(d.code, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
				+ ',[title] = ' + isnull('''' + replace(d.title, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10)
				+ ',[subtitle] = ' + isnull('''' + replace(d.subtitle, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
				+ ',[users] = ' + isnull('''' + replace(d.users, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
				+ ',[roles] = ' + isnull('''' + replace(d.roles, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10)
				+ ' where id = @dashboardID;' + CHAR(13)+CHAR(10) 
		+ ' end; else begin' + CHAR(13)+CHAR(10) 
			+ ' insert into as_dashboards ([code],[title],[subtitle],[users],[roles]) VALUES ( ' + CHAR(13)+CHAR(10)
				+ stuff(COALESCE(', ''' + RTRIM(replace(d.code, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(d.title, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10) 
					+ COALESCE(', ''' + RTRIM(replace(d.subtitle, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(d.users, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(d.roles, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+'); ' + CHAR(13)+CHAR(10) 
				, 1, 2, '')
			+ 'select @dashboardID = scope_identity(); end;' + CHAR(13)+CHAR(10)
			+ 'delete from as_dashboardPanels where as_dashboardPanels.dashboardID = @dashboardID;' + CHAR(13)+CHAR(10)
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'set @dashboardID = 0;' + CHAR(13)+CHAR(10)
			+ 'insert into #errors values(''dashboard'', ' 
				+ isnull('''' + replace(d.code, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+CHAR(10)
		+ (select 'begin try' + CHAR(13)+CHAR(10) 			
			+ ' insert into as_dashboardPanels ([dashboardID],[title],[ord],[col],[html],[code]' + CHAR(13)+CHAR(10)
				+ ',[cacheMinutes],[type],[isDisabled],[height]) VALUES ( @dashboardID, ' + CHAR(13)+CHAR(10)		
					+ stuff(COALESCE(', ''' + RTRIM(replace(dp.title, '''', '''''')) + '''', ', null')
						+ COALESCE(', ' + RTRIM(dp.ord), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.col), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.html, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.code, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.cacheMinutes), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.type, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.isDisabled), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.height), ', null') + CHAR(13)+CHAR(10)
					, 1, 2, '') + ');' + CHAR(13)+CHAR(10)
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'insert into #errors values(''dashboardPanel'', ' 
				+ isnull('''' + replace(dp.code, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+CHAR(10) from as_dashboardPanels as dp where d.id = dp.dashboardID FOR XML PATH (''),TYPE).value('.','NVARCHAR(MAX)')
		+ 'declare @name nvarchar(256), @sqlExpec nvarchar(500);' + CHAR(13)+CHAR(10)
		+ 'declare cur CURSOR LOCAL for
			select o.name from sys.objects as o where o.name like ''dashboard_' + d.code + '[_]%'' AND type in (N''P'', N''PC'')' + CHAR(13)+CHAR(10)
		+ 'open cur fetch next from cur into @name' + CHAR(13)+CHAR(10)
		+ 'while @@FETCH_STATUS = 0 BEGIN' + CHAR(13)+CHAR(10)
			+ 'begin try'  + CHAR(13)+CHAR(10)
				+ 'set @sqlExpec = ''drop procedure '' + @name' + CHAR(13)+CHAR(10)
				+ 'exec sp_executesql @sqlExpec' + CHAR(13)+CHAR(10)								
			+ 'end try' + CHAR(13)+CHAR(10)
			+ 'begin catch' + CHAR(13)+CHAR(10)
				+ 'insert into #errors values(''dashboardProc'', ' 
					+ isnull('''' + replace(d.code, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
			+ 'end catch' + CHAR(13)+CHAR(10)
			+ 'fetch next from cur into @name END' + CHAR(13)+CHAR(10)
		+ 'close cur deallocate cur' + CHAR(13)+CHAR(10)
		+ (select COALESCE('begin try exec sp_executesql N''' + replace((select OBJECT_DEFINITION (o.object_id)), '''', '''''') + '''' + CHAR(13)+CHAR(10) 
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'insert into #errors values(''dashboardProc'', ' 
				+ isnull('''' + replace(o.name, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+CHAR(10), '') AS [text()]
			 from  sys.objects as o where o.name like 'dashboard_'+ d.code +'[_]%' FOR XML PATH (''),TYPE).value('.','NVARCHAR(MAX)')		
		+ 'select * from #errors; drop table #errors;' as Result from as_dashboards as d where d.code = @code order by d.id;				