IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = 
            OBJECT_ID(N'dbo.as_system_getSQL_dashboards'))
	DROP PROCEDURE dbo.as_system_getSQL_dashboards
GO

create proc as_system_getSQL_dashboards @code nvarchar(32) as
select top 1 cast('' as nvarchar(max)) + 'declare @dashboardID int; set @dashboardID = null; ' + CHAR(13)+CHAR(10)
	+ 'create table #errors (type nvarchar(32), code nvarchar(256), message nvarchar(2048));' + CHAR(13)+CHAR(10)
	+ 'select top 1 @dashboardID = d.id from as_dashboards as d where d.code = ' + isnull('''' + d.code + '''', 'null') + ' order by d.id; ' + CHAR(13)+CHAR(10)
	+ 'begin try' + CHAR(13)+CHAR(10)
		+ 'if @dashboardID > 0 begin ' + CHAR(13)+CHAR(10) 
			+'update as_dashboards set [code] = ' + isnull('''' + replace(d.code, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
				+ ',[title] = ' + isnull('''' + replace(d.title, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10)
				+ ',[subtitle] = ' + isnull('''' + replace(d.subtitle, '''', '''''') + '''', 'null') + CHAR(13)+CHAR(10) 
				+ ',[users] = ' + isnull('''' + replace(d.users, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10) 
				+ ',[roles] = ' + isnull('''' + replace(d.roles, '''', '''''') + '''', 'null')  + CHAR(13)+CHAR(10)
				+ ' where id = @dashboardID;' + CHAR(13)+CHAR(10) 
		+ ' end; else begin' + CHAR(13)+CHAR(10) 
			+ ' insert into as_dashboards ([code],[title],[subtitle],[users],[roles]) VALUES ( ' + CHAR(13)+CHAR(10)
				+ stuff(COALESCE(', ''' + RTRIM(replace(d.code, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(d.title, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10) 
					+ COALESCE(', ''' + RTRIM(replace(d.subtitle, '''', '''''')) + '''', ', null')
					+ COALESCE(', ''' + RTRIM(replace(d.users, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+ COALESCE(', ''' + RTRIM(replace(d.roles, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
					+'); ' + CHAR(13)+CHAR(10) 
				, 1, 2, '')
			+ 'select @dashboardID = scope_identity(); end;' + CHAR(13)+CHAR(10)
			+ 'delete from as_dashboardPanels where as_dashboardPanels.dashboardID = @dashboardID;' + CHAR(13)+CHAR(10)
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'set @dashboardID = 0;' + CHAR(13)+CHAR(10)
			+ 'insert into #errors values(''dashboard'', ' 
				+ isnull('''' + replace(d.code, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+CHAR(10)
		+ (select 'begin try' + CHAR(13)+CHAR(10) 			
			+ ' insert into as_dashboardPanels ([dashboardID],[title],[ord],[col],[html],[code]' + CHAR(13)+CHAR(10)
				+ ',[cacheMinutes],[type],[isDisabled],[height]) VALUES ( @dashboardID, ' + CHAR(13)+CHAR(10)		
					+ stuff(COALESCE(', ''' + RTRIM(replace(dp.title, '''', '''''')) + '''', ', null')
						+ COALESCE(', ' + RTRIM(dp.ord), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.col), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.html, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.code, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.cacheMinutes), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ''' + RTRIM(replace(dp.type, '''', '''''')) + '''', ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.isDisabled), ', null') + CHAR(13)+CHAR(10)
						+ COALESCE(', ' + RTRIM(dp.height), ', null') + CHAR(13)+CHAR(10)
					, 1, 2, '') + ');' + CHAR(13)+CHAR(10)
		+ 'end try' + CHAR(13)+CHAR(10)
		+ 'begin catch' + CHAR(13)+CHAR(10)
			+ 'insert into #errors values(''dashboardPanel'', ' 
				+ isnull('''' + replace(dp.code, '''', '''''') + ''' ,', 'null ,') + 'error_message());' + CHAR(13)+CHAR(10)
		+ 'end catch' + CHAR(13)+CHAR(10) from as_dashboardPanels as dp where d.id = dp.dashboardID FOR XML PATH (''),TYPE).value('.','NVARCHAR(MAX)')
		+ 'select * from #errors; drop table #errors;' + CHAR(13)+CHAR(10)
		+ dbo.as_system_getSQL_procs ('dashboard', @code) + CHAR(13)+CHAR(10)		
		as Result from as_dashboards as d where d.code = @code order by d.id;